"""empty message

Revision ID: 8d35fd7d5dd2
Revises: c232f9b85c67
Create Date: 2022-03-21 20:09:42.097927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d35fd7d5dd2'
down_revision = 'c232f9b85c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('StarUser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('USER_FNAME', sa.String(length=250), nullable=False),
    sa.Column('USER_LNAME', sa.String(length=250), nullable=False),
    sa.Column('USER_EMAIL', sa.String(length=250), nullable=False),
    sa.Column('USER_PASSWORD', sa.String(length=250), nullable=False),
    sa.Column('USER_FAVORITE_LIST', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['USER_FAVORITE_LIST'], ['Favorites_List.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('User')
    op.drop_table('Userr')
    op.drop_constraint('Favorites_List_ibfk_3', 'Favorites_List', type_='foreignkey')
    op.create_foreign_key(None, 'Favorites_List', 'StarUser', ['USER_ID'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Favorites_List', type_='foreignkey')
    op.create_foreign_key('Favorites_List_ibfk_3', 'Favorites_List', 'Userr', ['USER_ID'], ['id'])
    op.create_table('Userr',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('USER_FNAME', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('USER_LNAME', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('USER_EMAIL', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('USER_PASSWORD', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('USER_FAVORITE_LIST', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['USER_FAVORITE_LIST'], ['Favorites_List.id'], name='Userr_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('User',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('USER_FNAME', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('USER_LNAME', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('USER_EMAIL', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('USER_PASSWORD', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('USER_FAVORITE_LIST', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['USER_FAVORITE_LIST'], ['Favorites_List.id'], name='User_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('StarUser')
    # ### end Alembic commands ###
