"""empty message

Revision ID: 91536577c80e
Revises: 4fff0e7fd207
Create Date: 2022-03-28 16:51:02.754883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91536577c80e'
down_revision = '4fff0e7fd207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Favorites_List_ibfk_3', 'Favorites_List', type_='foreignkey')
    op.drop_column('Favorites_List', 'USER_ID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Favorites_List', sa.Column('USER_ID', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Favorites_List_ibfk_3', 'Favorites_List', 'User', ['USER_ID'], ['id'])
    # ### end Alembic commands ###
