"""empty message

Revision ID: b5fbebabae00
Revises: b7897cc61dcf
Create Date: 2022-03-18 23:05:00.358893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5fbebabae00'
down_revision = 'b7897cc61dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Userr', sa.Column('USER_FAVORITE_LIST', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Userr', 'Favorites_List', ['USER_FAVORITE_LIST'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Userr', type_='foreignkey')
    op.drop_column('Userr', 'USER_FAVORITE_LIST')
    # ### end Alembic commands ###
