"""empty message

Revision ID: d23fe3f25de3
Revises: 8d35fd7d5dd2
Create Date: 2022-03-21 20:11:41.960977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd23fe3f25de3'
down_revision = '8d35fd7d5dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('USER_FNAME', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('USER_LNAME', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('USER_EMAIL', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('USER_PASSWORD', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('USER_FAVORITE_LIST', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['USER_FAVORITE_LIST'], ['Favorites_List.id'], name='User_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user')
    # ### end Alembic commands ###
